#!/bin/sh -xeu
dir="$(dirname -- "$0")"

docker build --pull "$dir" "$@" # --progress=plain
docker image save "$(docker build -q --pull "$dir" "$@")" | tar x -O --wildcards "*/layer.tar" | tar x -C "$dir"
