#!/bin/sh

test -f /etc/modules && sed '/^#/d' < /etc/modules | xargs -r -n 1 /sbin/modprobe

mkdir -p /mnt
mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mkdir -p /boot/efi
mount /dev/sda2 /boot/efi
ln -s /boot/efi /storage

ip link set dev eth0 up &
udhcpc &
for i in $(seq 5); do openvt sh; done

# qemu-system-x86_64 -smbios type=11,values=eval:...
oem_strings=""
if test -e /sys/firmware/dmi/entries/11-0/raw; then
  oem_strings="$(tail -c+6 /sys/firmware/dmi/entries/11-0/raw | tr '\0' '\n')"
fi

item() {
  printf %s "$1" | grep "^$2:" | tail "-c+$((${#2} + 2))"
}

eval="$(item "$oem_strings" eval)"
if test "$eval"; then
  eval "$eval"
fi

loop="$(item "$oem_strings" loop)"
if test "$loop"; then
  while true; do
    eval "$loop"
  done
fi

setsid -c sh

umount -a -r -d 2>&1 | grep -v "can't unmount /:" >&2
exec poweroff -f
