#!/bin/sh

test -f /etc/modules && sed '/^#/d' < /etc/modules | xargs -r -n 1 /sbin/modprobe

mkdir -p /mnt
mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

ip link set dev eth0 up &
udhcpc &
sh

umount -a -r -d 2>&1 | grep -v "can't unmount /:" >&2
exec reboot -f
